columns:
- customerID : category
- gender : category
- SeniorCitizen : int
- Partner : category
- Dependents : category
- tenure : int
- PhoneService : category
- MultipleLines : category
- InternetService : category
- OnlineSecurity : category
- OnlineBackup : category
- DeviceProtection : category
- TechSupport : category
- StreamingTV : category
- StreamingMovies : category
- Contract : category
- PaperlessBilling : category
- PaymentMethod : category
- MonthlyCharges : float
- TotalCharges : category
- Churn : object

numerical_columns:
- SeniorCitizen
- tenure
- MonthlyCharges
 
categorical_columns:
- customerID
- gender
- Partner
- Dependents
- PhoneService
- MultipleLines
- InternetService
- OnlineSecurity
- OnlineBackup
- DeviceProtection
- TechSupport
- StreamingTV
- StreamingMovies
- Contract
- PaperlessBilling
- PaymentMethod
- TotalCharges
- Churn

drop_columns:
- customerID
- PhoneService
- MultipleLines

# for data transformation
num_features:
- tenure
- MonthlyCharges
- TotalCharges

binary_cols:
- Partner
- Dependents
- OnlineSecurity
- OnlineBackup
- DeviceProtection
- TechSupport
- StreamingTV
- StreamingMovies
- PaperlessBilling
oh_columns:
- Contract
- PaymentMethod
- InternetService
- gender

transform_columns:
- MonthlyCharges
- TotalCharges
- tenure